import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 1,
            name: 'Apple MacBook Pro 16" M3 Max',
            description: 'The most powerful MacBook Pro ever with M3 Max chip, 36GB unified memory, and 1TB SSD. Perfect for professional content creators and developers.',
            price: 3499.99,
            originalPrice: 3999.99,
            stock: 15,
            sku: 'ELEC-MBP-001',
            rating: 4.9,
            reviewCount: 847,
            viewCount: 8942,
            isNew: true,
            isSale: true,
            discount: '12% OFF',
            colors: ['Space Gray', 'Silver'],
            sizes: ['16-inch'],
            features: ['M3 Max chip', '36GB RAM', '1TB SSD', 'Liquid Retina XDR display'],
            specifications: { processor: 'Apple M3 Max', ram: '36GB', storage: '1TB SSD', display: '16.2-inch' },
            tags: ['laptop', 'apple', 'professional', 'high-performance'],
            mainImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 1,
            name: 'Sony WH-1000XM5 Wireless Headphones',
            description: 'Industry-leading noise cancellation with premium sound quality. 30-hour battery life and crystal-clear hands-free calling.',
            price: 349.99,
            originalPrice: 399.99,
            stock: 42,
            sku: 'ELEC-SONY-002',
            rating: 4.8,
            reviewCount: 623,
            viewCount: 5832,
            isNew: false,
            isSale: true,
            discount: '13% OFF',
            colors: ['Black', 'Silver', 'Blue'],
            sizes: ['One Size'],
            features: ['Active Noise Cancellation', '30-hour battery', 'Multipoint connectivity', 'Touch controls'],
            specifications: { battery: '30 hours', connectivity: 'Bluetooth 5.2', weight: '250g' },
            tags: ['headphones', 'sony', 'wireless', 'noise-cancelling'],
            mainImage: 'https://images.unsplash.com/photo-1545127398-14699f92334b',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 2,
            name: 'Premium Cotton Henley Shirt',
            description: 'Soft, breathable cotton henley with a modern fit. Perfect for casual wear or layering. Made from 100% organic cotton.',
            price: 39.99,
            originalPrice: 59.99,
            stock: 128,
            sku: 'CLOTH-HEN-003',
            rating: 4.6,
            reviewCount: 342,
            viewCount: 3241,
            isNew: false,
            isSale: true,
            discount: '33% OFF',
            colors: ['Navy', 'Charcoal', 'Olive', 'White'],
            sizes: ['S', 'M', 'L', 'XL', 'XXL'],
            features: ['100% Organic Cotton', 'Button placket', 'Modern fit', 'Machine washable'],
            specifications: { material: 'Organic Cotton', fit: 'Modern', care: 'Machine wash cold' },
            tags: ['casual', 'shirt', 'cotton', 'organic'],
            mainImage: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 2,
            name: 'Slim Fit Denim Jeans',
            description: 'Classic slim-fit jeans with stretch denim for all-day comfort. Five-pocket styling with a modern tapered leg.',
            price: 79.99,
            originalPrice: null,
            stock: 95,
            sku: 'CLOTH-DEN-004',
            rating: 4.7,
            reviewCount: 528,
            viewCount: 4521,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Dark Wash', 'Light Wash', 'Black'],
            sizes: ['28', '30', '32', '34', '36', '38'],
            features: ['Stretch denim', 'Slim fit', 'Five-pocket design', 'Button fly'],
            specifications: { material: '98% Cotton, 2% Elastane', fit: 'Slim', rise: 'Mid-rise' },
            tags: ['jeans', 'denim', 'pants', 'casual'],
            mainImage: 'https://images.unsplash.com/photo-1542272454315-7f6fabf96e6e',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 3,
            name: 'Modern Ceramic Table Lamp',
            description: 'Elegant ceramic table lamp with linen shade. Perfect for bedside tables or living room accent lighting.',
            price: 89.99,
            originalPrice: 119.99,
            stock: 34,
            sku: 'HOME-LAMP-005',
            rating: 4.5,
            reviewCount: 189,
            viewCount: 2341,
            isNew: false,
            isSale: true,
            discount: '25% OFF',
            colors: ['White', 'Beige', 'Gray'],
            sizes: ['Standard'],
            features: ['Ceramic base', 'Linen shade', 'E26 bulb socket', 'Rotary switch'],
            specifications: { height: '22 inches', base: '6 inches diameter', bulb: 'E26 60W max' },
            tags: ['lamp', 'lighting', 'home-decor', 'ceramic'],
            mainImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 3,
            name: 'Luxury Velvet Throw Pillows Set',
            description: 'Set of 2 premium velvet throw pillows with hidden zipper closure. Soft, plush texture adds elegance to any room.',
            price: 44.99,
            originalPrice: null,
            stock: 67,
            sku: 'HOME-PIL-006',
            rating: 4.8,
            reviewCount: 412,
            viewCount: 3892,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Emerald Green', 'Navy Blue', 'Burgundy', 'Gold'],
            sizes: ['18x18 inches', '20x20 inches'],
            features: ['Velvet cover', 'Hidden zipper', 'Machine washable cover', 'Includes inserts'],
            specifications: { material: 'Velvet polyester', fill: 'Polyester fiber', count: '2 pillows' },
            tags: ['pillows', 'home-decor', 'velvet', 'luxury'],
            mainImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 4,
            name: 'Professional Yoga Mat with Strap',
            description: 'Eco-friendly TPE yoga mat with superior grip and cushioning. Includes carrying strap and alignment marks.',
            price: 49.99,
            originalPrice: 69.99,
            stock: 156,
            sku: 'SPRT-YOG-007',
            rating: 4.7,
            reviewCount: 734,
            viewCount: 6234,
            isNew: false,
            isSale: true,
            discount: '29% OFF',
            colors: ['Purple', 'Blue', 'Pink', 'Black'],
            sizes: ['72x24 inches'],
            features: ['Non-slip surface', '6mm thickness', 'Eco-friendly TPE', 'Alignment marks'],
            specifications: { material: 'TPE', thickness: '6mm', dimensions: '72x24 inches', weight: '2.2 lbs' },
            tags: ['yoga', 'fitness', 'exercise', 'mat'],
            mainImage: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 4,
            name: 'Adjustable Dumbbell Set 50lbs',
            description: 'Space-saving adjustable dumbbells with quick-change weight system. Perfect for home gym workouts.',
            price: 299.99,
            originalPrice: null,
            stock: 28,
            sku: 'SPRT-DUM-008',
            rating: 4.9,
            reviewCount: 567,
            viewCount: 7821,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Black/Red'],
            sizes: ['5-50 lbs per dumbbell'],
            features: ['Quick-change system', 'Space-saving design', 'Durable coating', 'Includes stand'],
            specifications: { range: '5-50 lbs', increment: '5 lbs', count: '2 dumbbells' },
            tags: ['dumbbells', 'fitness', 'home-gym', 'weights'],
            mainImage: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 5,
            name: 'Atomic Habits by James Clear',
            description: 'The groundbreaking book on habit formation. Learn how to build good habits and break bad ones with proven strategies.',
            price: 16.99,
            originalPrice: 27.00,
            stock: 243,
            sku: 'BOOK-ATH-009',
            rating: 4.8,
            reviewCount: 892,
            viewCount: 8234,
            isNew: false,
            isSale: true,
            discount: '37% OFF',
            colors: ['Hardcover', 'Paperback'],
            sizes: ['Standard'],
            features: ['Bestseller', 'Practical strategies', 'Science-backed', '320 pages'],
            specifications: { author: 'James Clear', pages: '320', publisher: 'Avery', year: '2018' },
            tags: ['self-help', 'habits', 'productivity', 'bestseller'],
            mainImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 5,
            name: 'The Psychology of Money',
            description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel. Essential reading for understanding financial success.',
            price: 18.99,
            originalPrice: null,
            stock: 187,
            sku: 'BOOK-PSY-010',
            rating: 4.7,
            reviewCount: 654,
            viewCount: 5932,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Hardcover', 'Paperback'],
            sizes: ['Standard'],
            features: ['Wall Street Journal Bestseller', 'Financial wisdom', '256 pages', 'Easy to read'],
            specifications: { author: 'Morgan Housel', pages: '256', publisher: 'Harriman House', year: '2020' },
            tags: ['finance', 'investing', 'money', 'bestseller'],
            mainImage: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d',
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 6,
            name: 'Luxury Skincare Set with Vitamin C',
            description: 'Complete skincare routine with Vitamin C serum, hyaluronic acid moisturizer, and gentle cleanser. Dermatologist-tested.',
            price: 79.99,
            originalPrice: 119.99,
            stock: 89,
            sku: 'BEAU-SKI-011',
            rating: 4.6,
            reviewCount: 423,
            viewCount: 4621,
            isNew: false,
            isSale: true,
            discount: '33% OFF',
            colors: ['Standard'],
            sizes: ['Full Size Set'],
            features: ['Vitamin C serum', 'Hyaluronic acid', 'Dermatologist-tested', 'Cruelty-free'],
            specifications: { items: '3 products', serumSize: '30ml', moisturizerSize: '50ml', cleanserSize: '150ml' },
            tags: ['skincare', 'beauty', 'vitamin-c', 'anti-aging'],
            mainImage: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571',
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 6,
            name: 'Professional Makeup Brush Set',
            description: 'Premium 12-piece makeup brush set with synthetic bristles and ergonomic handles. Includes storage case.',
            price: 59.99,
            originalPrice: null,
            stock: 124,
            sku: 'BEAU-MKP-012',
            rating: 4.8,
            reviewCount: 512,
            viewCount: 5128,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Rose Gold', 'Black', 'Silver'],
            sizes: ['12-piece set'],
            features: ['Synthetic bristles', 'Vegan-friendly', 'Professional quality', 'Storage case included'],
            specifications: { count: '12 brushes', material: 'Synthetic', handle: 'Aluminum', case: 'Included' },
            tags: ['makeup', 'brushes', 'beauty', 'professional'],
            mainImage: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796',
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 7,
            name: 'LEGO Architecture Skyline Collection',
            description: 'Build iconic city skylines with this detailed LEGO set. Perfect for display and creative building for ages 12+.',
            price: 49.99,
            originalPrice: 59.99,
            stock: 76,
            sku: 'TOY-LEG-013',
            rating: 4.9,
            reviewCount: 678,
            viewCount: 6892,
            isNew: false,
            isSale: true,
            discount: '17% OFF',
            colors: ['New York', 'London', 'Paris'],
            sizes: ['Standard'],
            features: ['597 pieces', 'Display stand', 'Collectible', 'Ages 12+'],
            specifications: { pieces: '597', difficulty: 'Intermediate', ageRange: '12+', dimensions: '10x4x3 inches' },
            tags: ['lego', 'building', 'architecture', 'collectible'],
            mainImage: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b',
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 7,
            name: 'Remote Control Racing Drone',
            description: 'High-speed racing drone with 720p camera and LED lights. Easy to fly with headless mode for beginners.',
            price: 129.99,
            originalPrice: null,
            stock: 45,
            sku: 'TOY-DRN-014',
            rating: 4.5,
            reviewCount: 289,
            viewCount: 3421,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Black/Blue', 'Black/Red'],
            sizes: ['Standard'],
            features: ['720p camera', 'LED lights', 'Headless mode', '15-min flight time'],
            specifications: { camera: '720p', range: '100m', battery: '15 minutes', speed: '30 mph' },
            tags: ['drone', 'rc', 'camera', 'racing'],
            mainImage: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 8,
            name: 'Modern L-Shaped Desk with Storage',
            description: 'Spacious L-shaped corner desk with built-in storage shelves. Perfect for home office or gaming setup.',
            price: 399.99,
            originalPrice: 549.99,
            stock: 23,
            sku: 'FURN-DSK-015',
            rating: 4.7,
            reviewCount: 456,
            viewCount: 5234,
            isNew: false,
            isSale: true,
            discount: '27% OFF',
            colors: ['Black', 'White', 'Walnut'],
            sizes: ['L-Shape 59x51 inches'],
            features: ['Storage shelves', 'Cable management', 'Sturdy steel frame', 'Easy assembly'],
            specifications: { dimensions: '59x51x29 inches', material: 'Wood/Metal', weight: '85 lbs', capacity: '200 lbs' },
            tags: ['desk', 'office', 'furniture', 'workspace'],
            mainImage: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2',
            createdAt: new Date('2024-02-17').toISOString(),
            updatedAt: new Date('2024-02-17').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 8,
            name: 'Ergonomic Office Chair with Lumbar Support',
            description: 'Premium mesh office chair with adjustable lumbar support, armrests, and headrest. Built for all-day comfort.',
            price: 279.99,
            originalPrice: null,
            stock: 38,
            sku: 'FURN-CHR-016',
            rating: 4.8,
            reviewCount: 723,
            viewCount: 7892,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Black', 'Gray'],
            sizes: ['Standard'],
            features: ['Adjustable lumbar support', 'Breathable mesh', '360° swivel', 'Tilt function'],
            specifications: { material: 'Mesh/Foam', capacity: '300 lbs', height: 'Adjustable 18-21 inches', warranty: '5 years' },
            tags: ['chair', 'office', 'ergonomic', 'furniture'],
            mainImage: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8',
            createdAt: new Date('2024-02-19').toISOString(),
            updatedAt: new Date('2024-02-19').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 1,
            name: 'Samsung 65" 4K QLED Smart TV',
            description: 'Stunning 4K QLED display with quantum dot technology. Built-in streaming apps and voice control.',
            price: 1299.99,
            originalPrice: 1799.99,
            stock: 19,
            sku: 'ELEC-TV-017',
            rating: 4.8,
            reviewCount: 534,
            viewCount: 6234,
            isNew: false,
            isSale: true,
            discount: '28% OFF',
            colors: ['Titan Gray'],
            sizes: ['65-inch'],
            features: ['4K QLED', 'Quantum Processor', 'Smart TV', 'Voice control'],
            specifications: { resolution: '3840x2160', refresh: '120Hz', hdmi: '4 ports', smart: 'Tizen OS' },
            tags: ['tv', 'samsung', '4k', 'smart-tv'],
            mainImage: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1',
            createdAt: new Date('2024-02-21').toISOString(),
            updatedAt: new Date('2024-02-21').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 2,
            name: 'Leather Crossbody Messenger Bag',
            description: 'Genuine leather messenger bag with adjustable strap and multiple compartments. Perfect for work or travel.',
            price: 149.99,
            originalPrice: 229.99,
            stock: 54,
            sku: 'CLOTH-BAG-018',
            rating: 4.7,
            reviewCount: 387,
            viewCount: 4123,
            isNew: false,
            isSale: true,
            discount: '35% OFF',
            colors: ['Brown', 'Black', 'Tan'],
            sizes: ['Medium', 'Large'],
            features: ['Genuine leather', 'Multiple compartments', 'Laptop sleeve', 'Adjustable strap'],
            specifications: { material: 'Full-grain leather', dimensions: '15x11x4 inches', laptop: 'Fits 15 inch' },
            tags: ['bag', 'leather', 'messenger', 'accessories'],
            mainImage: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62',
            createdAt: new Date('2024-02-23').toISOString(),
            updatedAt: new Date('2024-02-23').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 3,
            name: 'Stainless Steel Cookware Set 10-Piece',
            description: 'Professional-grade stainless steel cookware with aluminum core for even heating. Dishwasher safe.',
            price: 249.99,
            originalPrice: null,
            stock: 67,
            sku: 'HOME-COK-019',
            rating: 4.6,
            reviewCount: 612,
            viewCount: 5821,
            isNew: true,
            isSale: false,
            discount: null,
            colors: ['Stainless Steel'],
            sizes: ['10-piece set'],
            features: ['Tri-ply construction', 'Oven safe 500°F', 'Dishwasher safe', 'Riveted handles'],
            specifications: { pieces: '10', material: 'Stainless steel', core: 'Aluminum', induction: 'Compatible' },
            tags: ['cookware', 'kitchen', 'stainless-steel', 'cooking'],
            mainImage: 'https://images.unsplash.com/photo-1584990347498-7432d2be889f',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            sellerId: 'sell_5aH7kM2pW8xQ9yV1',
            categoryId: 4,
            name: 'Resistance Bands Set with Handles',
            description: 'Complete resistance band set with 5 resistance levels, handles, door anchor, and ankle straps.',
            price: 34.99,
            originalPrice: 49.99,
            stock: 198,
            sku: 'SPRT-BND-020',
            rating: 4.5,
            reviewCount: 856,
            viewCount: 8234,
            isNew: false,
            isSale: true,
            discount: '30% OFF',
            colors: ['Multi-color'],
            sizes: ['5-piece set'],
            features: ['5 resistance levels', 'Door anchor', 'Ankle straps', 'Carrying bag'],
            specifications: { levels: '10-50 lbs', bands: '5', material: 'Latex', accessories: 'Complete set' },
            tags: ['resistance-bands', 'fitness', 'exercise', 'home-workout'],
            mainImage: 'https://images.unsplash.com/photo-1598632640487-6ea4a4e8b963',
            createdAt: new Date('2024-02-27').toISOString(),
            updatedAt: new Date('2024-02-27').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});