import { db } from '@/db';
import { sellerOrders } from '@/db/schema';

async function main() {
    const now = Date.now();
    const hoursAgo = (hours: number) => new Date(now - hours * 60 * 60 * 1000).toISOString();
    const daysAgo = (days: number) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

    const sampleSellerOrders = [
        {
            orderId: 'ORD-TECH-001',
            sellerId: 'seller_tech001',
            customerId: 'cust_2fK8jP9qL3mN4rT6',
            customerName: 'John Doe',
            customerEmail: 'customer@shop.com',
            productId: 1,
            productName: 'Apple MacBook Pro 16" M3 Max',
            quantity: 1,
            price: 3499.99,
            total: 3499.99,
            status: 'delivered',
            paymentStatus: 'paid',
            shippingAddress: '123 Main St, New York, NY 10001',
            trackingNumber: 'TRK-001-TECH',
            notes: null,
            createdAt: daysAgo(7),
            updatedAt: daysAgo(2),
        },
        {
            orderId: 'ORD-TECH-002',
            sellerId: 'seller_tech001',
            customerId: 'sell_5aH7kM2pW8xQ9yV1',
            customerName: 'Jane Smith',
            customerEmail: 'seller@shop.com',
            productId: 2,
            productName: 'Sony WH-1000XM5 Wireless Headphones',
            quantity: 2,
            price: 349.99,
            total: 699.98,
            status: 'shipped',
            paymentStatus: 'paid',
            shippingAddress: '456 Oak Ave, Los Angeles, CA 90001',
            trackingNumber: 'TRK-002-TECH',
            notes: 'Handle with care',
            createdAt: daysAgo(3),
            updatedAt: daysAgo(1),
        },
        {
            orderId: 'ORD-TECH-003',
            sellerId: 'seller_tech001',
            customerId: 'cust_2fK8jP9qL3mN4rT6',
            customerName: 'John Doe',
            customerEmail: 'customer@shop.com',
            productId: 17,
            productName: 'Samsung 65" 4K QLED Smart TV',
            quantity: 1,
            price: 1299.99,
            total: 1299.99,
            status: 'processing',
            paymentStatus: 'paid',
            shippingAddress: '123 Main St, New York, NY 10001',
            trackingNumber: null,
            notes: null,
            createdAt: daysAgo(1),
            updatedAt: daysAgo(1),
        },
        {
            orderId: 'ORD-TECH-004',
            sellerId: 'seller_tech001',
            customerId: 'sell_5aH7kM2pW8xQ9yV1',
            customerName: 'Jane Smith',
            customerEmail: 'seller@shop.com',
            productId: 1,
            productName: 'Apple MacBook Pro 16" M3 Max',
            quantity: 1,
            price: 3499.99,
            total: 3499.99,
            status: 'pending',
            paymentStatus: 'pending',
            shippingAddress: '456 Oak Ave, Los Angeles, CA 90001',
            trackingNumber: null,
            notes: null,
            createdAt: hoursAgo(5),
            updatedAt: hoursAgo(5),
        },
        {
            orderId: 'ORD-TECH-005',
            sellerId: 'seller_tech001',
            customerId: 'cust_2fK8jP9qL3mN4rT6',
            customerName: 'John Doe',
            customerEmail: 'customer@shop.com',
            productId: 2,
            productName: 'Sony WH-1000XM5 Wireless Headphones',
            quantity: 1,
            price: 349.99,
            total: 349.99,
            status: 'cancelled',
            paymentStatus: 'refunded',
            shippingAddress: '123 Main St, New York, NY 10001',
            trackingNumber: null,
            notes: 'Customer requested cancellation',
            createdAt: daysAgo(4),
            updatedAt: daysAgo(3),
        },
        {
            orderId: 'ORD-FASH-001',
            sellerId: 'seller_fashion002',
            customerId: 'cust_2fK8jP9qL3mN4rT6',
            customerName: 'John Doe',
            customerEmail: 'customer@shop.com',
            productId: 3,
            productName: 'Premium Cotton Henley Shirt',
            quantity: 3,
            price: 39.99,
            total: 119.97,
            status: 'delivered',
            paymentStatus: 'paid',
            shippingAddress: '123 Main St, New York, NY 10001',
            trackingNumber: 'TRK-001-FASH',
            notes: null,
            createdAt: daysAgo(10),
            updatedAt: daysAgo(6),
        },
        {
            orderId: 'ORD-FASH-002',
            sellerId: 'seller_fashion002',
            customerId: 'sell_5aH7kM2pW8xQ9yV1',
            customerName: 'Jane Smith',
            customerEmail: 'seller@shop.com',
            productId: 4,
            productName: 'Slim Fit Denim Jeans',
            quantity: 2,
            price: 79.99,
            total: 159.98,
            status: 'shipped',
            paymentStatus: 'paid',
            shippingAddress: '456 Oak Ave, Los Angeles, CA 90001',
            trackingNumber: 'TRK-002-FASH',
            notes: null,
            createdAt: daysAgo(4),
            updatedAt: daysAgo(2),
        },
        {
            orderId: 'ORD-FASH-003',
            sellerId: 'seller_fashion002',
            customerId: 'cust_2fK8jP9qL3mN4rT6',
            customerName: 'John Doe',
            customerEmail: 'customer@shop.com',
            productId: 18,
            productName: 'Leather Crossbody Messenger Bag',
            quantity: 1,
            price: 149.99,
            total: 149.99,
            status: 'processing',
            paymentStatus: 'paid',
            shippingAddress: '123 Main St, New York, NY 10001',
            trackingNumber: null,
            notes: null,
            createdAt: daysAgo(2),
            updatedAt: daysAgo(1),
        },
        {
            orderId: 'ORD-FASH-004',
            sellerId: 'seller_fashion002',
            customerId: 'sell_5aH7kM2pW8xQ9yV1',
            customerName: 'Jane Smith',
            customerEmail: 'seller@shop.com',
            productId: 3,
            productName: 'Premium Cotton Henley Shirt',
            quantity: 1,
            price: 39.99,
            total: 39.99,
            status: 'pending',
            paymentStatus: 'pending',
            shippingAddress: '456 Oak Ave, Los Angeles, CA 90001',
            trackingNumber: null,
            notes: null,
            createdAt: hoursAgo(6),
            updatedAt: hoursAgo(6),
        },
        {
            orderId: 'ORD-FASH-005',
            sellerId: 'seller_fashion002',
            customerId: 'cust_2fK8jP9qL3mN4rT6',
            customerName: 'John Doe',
            customerEmail: 'customer@shop.com',
            productId: 4,
            productName: 'Slim Fit Denim Jeans',
            quantity: 1,
            price: 79.99,
            total: 79.99,
            status: 'delivered',
            paymentStatus: 'paid',
            shippingAddress: '123 Main St, New York, NY 10001',
            trackingNumber: 'TRK-003-FASH',
            notes: 'Priority shipping',
            createdAt: daysAgo(8),
            updatedAt: daysAgo(5),
        },
    ];

    await db.insert(sellerOrders).values(sampleSellerOrders);
    
    console.log('✅ Seller orders seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});